//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEN.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BanTinTuKhoa
    {
        public int Id { get; set; }
        public int TuKhoaId { get; set; }
        public int BanTinId { get; set; }
    
        public virtual BanTin BanTin { get; set; }
        public virtual TuKhoa TuKhoa { get; set; }
    }
}
