//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEN.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BanTin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BanTin()
        {
            this.BanTinAnhs = new HashSet<BanTinAnh>();
            this.BanTinTuKhoas = new HashSet<BanTinTuKhoa>();
            this.BinhLuans = new HashSet<BinhLuan>();
            this.ChiaSes = new HashSet<ChiaS>();
            this.Likes = new HashSet<Like>();
        }
    
        public int BanTinId { get; set; }
        public int ThanhVienId { get; set; }
        public string NoiDung { get; set; }
        public System.DateTime ThoiGian { get; set; }
        public string The { get; set; }
        public Nullable<int> DiaDiemId { get; set; }
        public string QuyenRiengTu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BanTinAnh> BanTinAnhs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BanTinTuKhoa> BanTinTuKhoas { get; set; }
        public virtual DiaDiem DiaDiem { get; set; }
        public virtual ThanhVien ThanhVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BinhLuan> BinhLuans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiaS> ChiaSes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Like> Likes { get; set; }
    }
}
