//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEN.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BanTinAnh
    {
        public int IdAnh { get; set; }
        public int BanTinId { get; set; }
        public int TMAnhId { get; set; }
        public Nullable<int> ThanhVien_UserId { get; set; }
    
        public virtual BanTin BanTin { get; set; }
        public virtual ThanhVien ThanhVien { get; set; }
    }
}
