
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SEN.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class BinhLuan
{

    public int BinhLuanId { get; set; }

    public int BanTinId { get; set; }

    public int ThanhVienId { get; set; }

    public string NoiDung { get; set; }

    public Nullable<int> AnhId { get; set; }

    public System.DateTime ThoiGian { get; set; }

    public Nullable<int> DiaDiemId { get; set; }



    public virtual BanTin BanTin { get; set; }

}

}
