//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEN.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiaS
    {
        public int ChiaSeId { get; set; }
        public int BanTinId { get; set; }
        public string HinhThuc { get; set; }
        public System.DateTime ThoiGian { get; set; }
        public string QuyenRiengTu { get; set; }
        public string DiaDiem { get; set; }
    
        public virtual BanTin BanTin { get; set; }
    }
}
