
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SEN.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class DiaDiem
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public DiaDiem()
    {

        this.BanTins = new HashSet<BanTin>();

    }


    public int DiaDiemId { get; set; }

    public int TheDiaLy { get; set; }

    public int MaDiaLy { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<BanTin> BanTins { get; set; }

}

}
