
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SEN.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class ThongBao
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ThongBao()
    {

        this.Nhoms = new HashSet<Nhom>();

    }


    public int ThongBaoId { get; set; }

    public int ThanhVienId { get; set; }

    public System.DateTime ThoiGian { get; set; }

    public System.DateTime ThoiGianDaXem { get; set; }

    public string NoiDung { get; set; }

    public int BinhLuanId { get; set; }

    public int BanTinId { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Nhom> Nhoms { get; set; }

    public virtual ThanhVien ThanhVien { get; set; }

}

}
