//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEN.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TuKhoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TuKhoa()
        {
            this.BanTinTuKhoas = new HashSet<BanTinTuKhoa>();
        }
    
        public int TuKhoaId { get; set; }
        public int ThanhVienId { get; set; }
        public string NoiDung { get; set; }
        public Nullable<int> CountView { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BanTinTuKhoa> BanTinTuKhoas { get; set; }
    }
}
